name: 'AWS DEPLOY CODE'

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Using Node JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node}}
    - name: Caching Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm install
  aws-deploy:
    name: aws-deploy
    runs-on: ubuntu-latest
    needs: build-app
    strategy: 
      matrix:
        node: [18]
    steps:
    - uses: actions/checkout@v3
    - name: Load Cached Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Load Env Variable From Secret
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      run: | 
        chmod +x ./scripts/setAWSEnvironment.sh
        ./scripts/setAWSEnvironment.sh
    - name: Deploy Project
      run: yarn deploy
        
        




  