name: 'AWS DEPLOY CODE'

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14 , 16, 18]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Using Node JS
      uses: actions/setup-node@v3
      with:
        node-version: ${{matrix.node}}
    - name: Caching Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      run: npm install


  